name: pkg-pr-new
"on":
  push:
    branches:
      - main
  pull_request:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: |
          pnpx pkg-pr-new publish --comment=off \
            packages/ms-teams-webhook