name: pkg-pr-new
"on":
  push:
    branches:
      - main
  pull_request:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v4
        with:
          version: 9
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      
      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - run: |
          pnpx pkg-pr-new publish --comment=off \
            packages/ms-teams-webhook 